import { GeistSans } from "geist/font/sans";
import "./globals.css";

export const metadata = {
	title: "Front Desk",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${GeistSans.className} bg-primary`}>
				{children}
			</body>
		</html>
	);
}
