import { GeistSans } from "geist/font/sans";
import { Poppins } from "next/font/google";

const poppins = Poppins({
	variable: "--display-font",
	subsets: ["latin"],
	weight: ["400", "500", "700"],
});

import "./globals.css";

export const metadata = {
	title: "Front Desk",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${GeistSans.className} ${poppins.className} bg-primary`}
			>
				{children}
			</body>
		</html>
	);
}
