import Icon from "../components/common/icon/Icon";

export const optionsFrom = {
	autoHide: true,
	todayBtn: false,
	clearBtn: false,
	clearBtnText: "Clear",
	maxDate: new Date("2030-01-01"),
	minDate: new Date("2000-01-01"),
	theme: {
		background: "bg-secondary p-0",
		todayBtn: "",
		clearBtn: "",
		icons: "",
		text: "!font-sm !font-normal leading-5 !hover:text-zinc-900",
		disabledText: "!text-zinc-400 !font-sm !font-normal leading-5",
		input: "",
		inputIcon: "",
		selected: "!text-zinc-900 !font-normal !hover:text-zinc-900 !font-sm",
	},
	icons: {
		prev: () => <Icon src={"prev"} width={36} height={36} mr={0} />,
		next: () => <Icon src={"next-arrow"} width={36} height={36} mr={0} />,
	},
	datepickerClassNames: "calendarBox",
	defaultDate: new Date(),
	language: "en",
	disabledDates: [],
	weekDays: ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"],
	inputNameProp: "dateFrom",
	inputIdProp: "dateFrom",
	inputPlaceholderProp: "Pick a date",
	inputDateFormatProp: {
		day: "numeric",
		month: "long",
		year: "numeric",
	},
};

export const optionsTo = {
	autoHide: true,
	todayBtn: false,
	clearBtn: false,
	clearBtnText: "Clear",
	maxDate: new Date("2030-01-01"),
	minDate: new Date("2000-01-01"),
	theme: {
		background: "bg-secondary p-0",
		todayBtn: "",
		clearBtn: "",
		icons: "",
		text: "!font-sm !font-normal leading-5 !hover:text-zinc-900",
		disabledText: "!text-zinc-400 !font-sm !font-normal leading-5",
		input: "",
		inputIcon: "",
		selected: "!text-zinc-900 !font-normal !hover:text-zinc-900 !font-sm",
	},
	icons: {
		prev: () => <Icon src={"prev"} width={36} height={36} mr={0} />,
		next: () => <Icon src={"next-arrow"} width={36} height={36} mr={0} />,
	},
	datepickerClassNames: "calendarBox",
	defaultDate: new Date(),
	language: "en",
	disabledDates: [],
	weekDays: ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"],
	inputNameProp: "dateTo",
	inputIdProp: "dateTo",
	inputPlaceholderProp: "Pick a date",
	inputDateFormatProp: {
		day: "numeric",
		month: "long",
		year: "numeric",
	},
};
